---
- hosts: localhost
  name: Creating new CPG
  gather_facts: true
  tasks:
    - name: Load Storage System Vars
      include_vars: 'login_all.yml'
    - name: Create CPG ansible_auto_CreateCPG-001 
      hpe3par_cpg: 
        storage_system_ip: sg5lab-001.3par
        storage_system_password: storage_system_username
        storage_system_username: storage_system_password
        state: present 
        cpg_name: ansible_auto_CreateCPG-001
        growth_increment: 32.5
        growth_increment_unit: GiB
        growth_limit: 65536
        growth_limit_unit: MiB
        growth_warning: 51200
        growth_warning_unit: MiB
        raid_type: R6
        set_size: 8
        high_availability: MAG
        disk_type: FC
    - debug: msg="ansible_auto_CreateCPG-001 CPG created"
