---

- hosts: localhost
  name: Create a Vlun in 3par
  gather_facts: true
  vars_prompt:
     - name: vlun_volume_name
       prompt: "Enter Volume name"
       private: no
     - name: vlun_host_name
       prompt: "Enter Host Name"
       private: no
     - name: cpg
       prompt: "Enter CPG like FC_r5,FC_r1,FC_r6,SSD_r1,SSD_r5 Name"
       private: no
     - name: size
       prompt: "Enter Volume size in GB"
       private: no
     - name: lunid
       prompt: "Enter Volume Number"
       private: no
  vars_files:
  - login_all.yml
  tasks:
  - name: Create VLUN in 3par
    hpe3par_volume: 
      storage_system_ip="{{ storage_system_ip }}"
      storage_system_username="{{ storage_system_username }}"
      storage_system_password="{{ storage_system_password }}"
      state=present
      volume_name="{{ vlun_volume_name }}"
      size="{{ size }}"
      size_unit=GiB
      cpg="{{ cpg }}"
  - name: Export the Volume to Hosts
    hpe3par_vlun: 
      storage_system_ip="{{ storage_system_ip }}"
      storage_system_username="{{ storage_system_username }}"
      storage_system_password="{{ storage_system_password }}"
      state=export_volume_to_host
      volume_name="{{ vlun_volume_name }}"
      host_name="{{ vlun_host_name }}"
      lunid="{{ lunid }}"
  - debug: msg="Volume {{ vlun_volume_name }} has been setup."
